version: '3.4'

networks:
    traefik-net:
        name: ${TRAEFIK_NETWORK_NAME}
        external: true
    dashboard-net:
        name: ${DASHBOARD_NETWORK_NAME}

volumes:
    typesense-data:

services:
    typesense-service:
        container_name: ${TYPESENSE_CONTAINER_NAME}
        image: ${TYPESENSE_IMAGE_NAME}:${TYPESENSE_IMAGE_TAG}
        restart: ${TYPESENSE_RESTART_POLICY}
        command: '--data-dir /data --api-key=xyz --enable-cors'
        ports:
            - "${TYPESENSE_HOST_PORT}:${TYPESENSE_CONTAINER_PORT}"
        volumes:
            - ./${TYPESENSE_VOLUME_NAME}:/data
        networks:
            - ${DASHBOARD_NETWORK_NAME}
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:50000"
                tag: ${DASHBOARD_CONTAINER_NAME}
    dashboard-service:
        container_name: ${DASHBOARD_CONTAINER_NAME}
        image: ${DASHBOARD_IMAGE_NAME}:${DASHBOARD_IMAGE_TAG}
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SHOWCASE_API=${SHOWCASE_API}
            - MOBILE_API=${MOBILE_API}
        restart: ${DASHBOARD_RESTART_POLICY}
        networks:
            - ${TRAEFIK_NETWORK_NAME}
            - ${DASHBOARD_NETWORK_NAME}
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:50000"
                tag: ${DASHBOARD_CONTAINER_NAME}
        # ports:
        #     - 3000:3000
        labels:
            # General traefik settings
            - "traefik.enable=true" # <== Enabling traefik to manage this container
            - "traefik.docker.network=${TRAEFIK_NETWORK_NAME}" # <== The network traefik will operate on the docker network named traefik-net
            # HTTP to HTTPS settings
            - "traefik.http.routers.dashboard-secure.entrypoints=websecure" # <== The entrypoint HTTPS
            - "traefik.http.routers.dashboard-secure.rule=Host(`${DASHBOARD_SUBDOMAIN}.${DOMAIN_NAME}`)" # <== The rule to match the request
            # Let's Encrypt settings
            - "traefik.http.routers.dashboard-secure.tls=true" # Enable TLS
            - "traefik.http.routers.dashboard-secure.tls.certresolver=lets-encrypt" # <== The certificate resolver to use
            # Traefik compress settings
            - "traefik.http.middlewares.dashboard-compress.compress=true" # <== Enable compression
            # Traefik header settings
            ## SSL settings
            - "traefik.http.middlewares.dashboard-header.headers.sslRedirect=true" # <== Enabling SSL redirection
            ## STS settings
            - "traefik.http.middlewares.dashboard-header.headers.stsSeconds=31536000" # <== Setting STS seconds
            - "traefik.http.middlewares.dashboard-header.headers.stsIncludeSubdomains=true" # <== Enabling STS include subdomain
            - "traefik.http.middlewares.dashboard-header.headers.stsPreload=true" # <== Enabling STS preload
            - "traefik.http.middlewares.dashboard-header.headers.forceSTSHeader=true" # <== Enabling force STS header
            ## Security settings
            - "traefik.http.middlewares.dashboard-header.headers.framedeny=true" # <== Preventing clickjacking
            - "traefik.http.middlewares.dashboard-header.headers.browserxssfilter=true" # <== Preventing XSS
            - "traefik.http.middlewares.dashboard-header.headers.referrerPolicy=same-origin" # <== Preventing Referrer leakage
            ## Cache settings
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.maxTtl=300" # <== Setting the max TTL time
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.maxAge=300" # <== Setting the max age time
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.maxStale=300" # <== Setting the max stale time
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.minFresh=300" # <== Setting the min fresh time
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.sharedMaxAge=300" # <== Setting the shared max age time
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.noCache=false" # <== Enabling cache
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.noStore=false" # <== Enabling store
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.noTransform=false" # <== Enabling transform
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.mustRevalidate=true" # <== Enabling revalidation
            - "traefik.http.middlewares.dashboard-header.plugin.httpCache.proxyRevalidate=true" # <== Enabling proxy revalidation
            # Traefik loadbalancer settings
            - "traefik.http.services.dashboard-secure.loadbalancer.server.port=${DASHBOARD_PORT}" # <== The port to use